#!/bin/bash

_debug() {

  local readonly msg="$1"

  echo "."
  echo "bodega >> [Debug] << ${msg}"
  echo "."
}


_error() {

  local readonly msg="$1"

  echo "."
  echo "."
  echo "bodega >> [Error] << ${msg}"
  echo "."
  echo "."

  return 1
}


_error_fatal() {

  local readonly msg="$1"

  echo "."
  echo "."
  echo "bodega >> [Fatal Error] << ${msg}"
  echo "."
  echo "."

  exit 1
}


_hw_check() {

  local cpu_arch
  local cpu_count

  read cpu_arch   <<< $( uname -p )
  read cpu_count  <<< $( getconf _NPROCESSORS_ONLN )

  [[ ${cpu_arch} =~ ${1,,} ]] \
    && [[ ${cpu_count} =~ ${2,,} ]]
}


_os_check_linux() {

  [[ -f /etc/os-release ]] && . /etc/os-release     \
    && [[ ${1,,} =~ ${ID}${ID:+|}${ID_LIKE// /|} ]]  \
    && [[ ${VERSION_ID} =~ ${2,,} ]]                  \
    && [[ ${CPE_NAME}   =~ ${3,,} ]]                   \
    && return 0

  return 1
}


_os_check_macos() {

  echo
}


_denote_varlist_outset() {

  local outset_vars

  read outset_vars <<< $(
    set 2>/dev/null | while read a
      do [[ $a == *=* ]] || break
        echo -n "${a:+ }${a/=*}"
      done
  )

  BODEGA_VARLIST_OUTSET="${outset_vars}"
}


_uptake_varlist_outset() {

  local uptake_vars="$@"
  local outset_vars

  read match_vars <<< $(
    echo $BODEGA_VARLIST_OUTSET ${uptake_vars} | tr ' ' '\n' | sort | uniq -d | tr '\n' ' '
  )

  read outset_vars <<< $(
    echo $BODEGA_VARLIST_OUTSET ${match_vars}  | tr ' ' '\n' | sort | uniq -u | tr '\n' ' '
  )

  BODEGA_VARLIST_OUTSET="${outset_vars}"
}


_accrue_varlist_cmake_definitions() {

  local current_vars
  local latest_vars
  local cmake_vars

  read current_vars <<< $(
    set 2>/dev/null | while read a
      do [[ $a == *=* ]] || break
        echo -n "${a:+ }${a/=*}"
      done
  )

  # find the symmetric difference of the two var sets (outset and current)
  read latest_vars <<< $(
    echo $BODEGA_VARLIST_OUTSET ${current_vars} | tr ' ' '\n' | sort | uniq -u | tr '\n' ' '
  )

  # isolate new vars that serve as cmake definitions
  read cmake_vars <<< $(
    echo ${latest_vars} | tr ' ' '\n' | grep "^CMAKE_*" | tr '\n' ' '
  )

  BODEGA_VARLIST_CMAKE_DEFINITIONS="${cmake_vars}"
}


_render_cmdline_cmake_definitions() {

  read cmake_defs <<< $(
  echo $BODEGA_VARLIST_CMAKE_DEFINITIONS | tr ' ' '\n' | while read a
    do [[ -n $a ]] || break
      echo -n "${a:+ }-D${a}=${!a}"
    done
    echo
  )

  BODEGA_CMDLINE_CMAKE_DEFINITIONS="${cmake_defs}"
}


_enact_defaults_cmake() {

  CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE:-Release}
}


_setup_nersc_cori_haswell() {

  # AVX2 only

  module load cmake
}


_setup_nersc_cori_knl_cross_compile_scenario() {

  # AVX512

  module load cmake

  # use flags to force cross-compile

  CMAKE_C_FLAGS="-axMIC-AVX512,AVX2"
  CMAKE_Fortran_FLAGS="-axMIC-AVX512,AVX2"

  # https://github.com/ORNL-Fusion/stellinstall/blob/02da8103a846ef80190adf052abacd9741447708/trunk/setup_cmake#L279
  # -DEXTRA_FLAGS="-qopenmp -axMIC-AVX512,AVX"
  echo
}


_setup_nersc_cori() {

  module load cmake

  # use intel compiler and openmpi wrapper
  CMAKE_Fortran_COMPILER=/opt/intel/compilers_and_libraries_2019.3.199/linux/bin/intel64/ifort
  module load openmpi
}


_setup_macos_github() {

  CMAKE_Fortran_COMPILER=/usr/local/opt/gfortran/bin/gfortran
}


_setup_ubuntu_github() {

  cat /etc/os-release
}


_setup_windows_github() {

 echo
}


__bodega_build() {

  _denote_varlist_outset

  _uptake_varlist_outset \
    CMAKE_BUILD_TYPE \
    CMAKE_Fortran_COMPILER

  _enact_defaults_cmake

  _accrue_varlist_cmake_definitions

  [[ $NERSC_HOST =~ cori ]]               \
    && _hw_check        "x86_64" "64|272"  \
    && _os_check_linux  "rhel"   "7.6"      \
    && _setup_nersc_cori

  [[ $BODEGA_OS == "macos-latest" ]] \
    && _setup_macos_github

  [[ $BODEGA_OS == "ubuntu-latest" ]] \
    && _setup_ubuntu_github \
    && _debug "BODEGA_OS is $BODEGA_OS"

  _accrue_varlist_cmake_definitions

  _render_cmdline_cmake_definitions

  echo; echo; _debug "print CMake definitions - BEGIN"
  echo; echo $BODEGA_CMDLINE_CMAKE_DEFINITIONS | tr ' ' '\n'
  echo; echo; _debug "print CMake definitions - END"
  echo; echo

  mkdir -p ./build && cd $_
  cmake $BODEGA_CMDLINE_CMAKE_DEFINITIONS .. && make


  # differentiate by:
    # - compute_env:   [ nersc github docker ]
    # - os_type:       [ ubuntu macos ]
    # - mpi_wrapper:   [ openmpi mpich intel ]
    # - 
}


__bodega_test() {

  cd ./build && make test
}


BODEGA_VARLIST_OUTSET=''
BODEGA_VARLIST_CMAKE_DEFINITIONS=''
BODEGA_CMDLINE_CMAKE_DEFINITIONS=''

[[ -n "$1" ]] && "__bodega_$1" "$@"


#BODEGA_BUILD_TYPE
#BODEGA_OS


#source ./cmake_definitions


#-DCMAKE_BUILD_TYPE=Debug
#-DCMAKE_BUILD_TYPE=Release

