#!/bin/bash

_debug() {

  local readonly msg="$1"

  echo "."
  echo "bodega >> [Debug] << ${msg}"
  echo "."
}


_error() {

  local readonly msg="$1"

  echo "."
  echo "."
  echo "bodega >> [Error] << ${msg}"
  echo "."
  echo "."

  return 1
}


_error_fatal() {

  local readonly msg="$1"

  echo "."
  echo "."
  echo "bodega >> [Fatal Error] << ${msg}"
  echo "."
  echo "."

  exit 1
}


_os_check() {

  . /etc/os-release

  [[ ${1,,} =~ ${ID}${ID:+|}${ID_LIKE// /|} ]] \
    && [[ ${VERSION_ID} =~ ${2,,} ]]           \
    && [[ ${CPE_NAME}   =~ ${3,,} ]]           \
    && return 0

  return 1
}


_setup_ubuntu() {

  sudo -- apt-get update
  sudo -- apt-get install cmake
}


_setup_macos() {

  brew install cmake
}


_yield_cmake_defs_default() {

  echo
}


_yield_cmake_defaults() {

  #local readonly origindir="$( pwd -P )"
  #local readonly scriptdir="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
  local item

  #cd $(mktemp -d) || return 1

  # https://unix.stackexchange.com/questions/3510/how-to-print-only-defined-variables-shell-and-or-environment-variables-in-bash
  #read outset_vars <<< $(
  #  set 2>/dev/null | while read a
  #    do [[ $a == *=* ]] || break
  #      echo ${a/=*}
  #    done
  #)

  # https://stackoverflow.com/questions/1305237/how-to-list-variables-declared-in-script-in-bash
  # read outset_vars <<< $( set -o posix ; set )

  while read item; do
    cmake_args="${cmake_args}${item:+ -D${item}}"
  done < <( cat <<-__EOF__

    CMAKE_BUILD_TYPE=Release
    CMAKE_Fortran_COMPILER=mpifort

	__EOF__
  )

  echo ${cmake_args}

  #set 2>/dev/null | while read a; do [[ $a == *=* ]] || break; echo ${a/=*}; done

  #cd -
  #[[ ${OLDPWD} != ${origindir} ]] && rm -rf ${OLDPWD}

  BODEGA_CMAKE_ARGS="${cmake_args}"

}


_cmake_intel() {

  echo
}


_cmake_mpiwrapper() {

  echo
}


_render_cmake_args() {

  env | grep "CMAKE_"
}


_cmake_ordinary() {

  mkdir -p ./build && cd $_
  cmake .. && make
}


__bodega_build() {

  _cmake_ordinary
}


__bodega_test() {

  echo
}


[[ -n "$1" ]] && "__bodega_$1" "$@"

#source ./cmake_definitions


#-DCMAKE_BUILD_TYPE=Debug
#-DCMAKE_BUILD_TYPE=Release

# ${CMAKE_BUILD_TYPE:+-DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE}

# -DCMAKE_Fortran_COMPILER=/usr/local/opt/gfortran/bin/gfortran
