#!/bin/bash

_error() {

  local readonly msg="$1"

  echo "."
  echo "."
  echo "bungalow >> [Error] << ${msg}"
  echo "."
  echo "."

  return 1
}


_error_fatal() {

  local readonly msg="$1"

  echo "."
  echo "."
  echo "bungalow >> [Fatal Error] << ${msg}"
  echo "."
  echo "."

  exit 1
}


_os_check() {

  . /etc/os-release

  [[ ${1,,} =~ ${ID}${ID:+|}${ID_LIKE// /|} ]] \
    && [[ ${VERSION_ID} =~ ${2,,} ]]           \
    && [[ ${CPE_NAME}   =~ ${3,,} ]]           \
    && return 0

  return 1
}


_yield_image_readybake() {

  local readonly outsetdir="${PWD}"
  cd $(mktemp -d) || return 1

  cat > ./Dockerfile <<-__EOF__

	FROM rikorose/gcc-cmake:gcc-10

	__EOF__

  echo; echo "${PWD}"; cat ./*; echo; echo; echo
  docker build --tag bungalow_readybake . || return 1

  cd -
  [[ ${OLDPWD} != ${outsetdir} ]] && rm -rf ${OLDPWD}
}


_yield_image_readybake_alpine() {

  local readonly outsetdir="${PWD}"
  cd $(mktemp -d) || _error_fatal "unable to allocate temp dir"

  cat > ./Dockerfile <<-__EOF__

	FROM alpine:3.14.2
	RUN set -x \
	  && apk add --no-cache \
	      cmake gfortran libgfortran netcdf-dev

	__EOF__

  cat > ./.env <<-__EOF__

	FC=gfortran
	CXX=g++
	NETCDF_FLAGS=" -D_NETCDF"
	L_NETCDF=" -L/usr/lib/x86_64-linux-gnu/lib -lnetcdff"
	I_NETCDF=" -I/usr/include"

	__EOF__

  echo; echo "${PWD}"; cat ./*; echo; echo; echo
  docker build --tag bungalow_readybake_alpine .

  cd -
  [[ "${OLDPWD}" != "${outsetdir}" ]] && rm -rf ${OLDPWD}
}


_yield_image_readybake_centos() {

  echo
}


_yield_image_readybake_debian() {

  echo
}


_yield_image_readybake_ubuntu() {

  echo
}


_ready_buildenv_cmake() {

  local readonly readybake_image="${1:=bungalow_readybake}"

  local container_id <<< $(
  	docker create --interactive --tty ${readybake_image}
  )

  [[ -n "${container_id}" ]] || return 1

  BUILDENV_CONTAINER_ID="${container_id}"
}


__bungalow_build() {

  local readonly os_id="${1,,}"

  _yield_image_readybake
  _ready_buildenv_cmake || _error_fatal ""

  echo
}


__bungalow_debug() {

  echo
}


BUILDENV_CONTAINER_ID=""


[[ -n "$1" ]] && "__bungalow_$1" "$@"

